[[questions]]
answers = [
    {text = "~~~txt\nHello World!\nYou said: a", response = "yay", correct = true},
    {text = "~~~txt\nHello World!\nYou said: b", response = "no"},
    {text = "~~~txt\na", response = "I mean, close?"},
    {text = "~~~txt\nisadoai\ndaskfaifj\n~~~", response = "what?"},
]
question = """
Consider the following code:

@code rust

    use std::io;

    fn main() {
        println!("Hello, world!");
        let mut input = String::new();
        io::stdin().read_line(&mut input).unwrap();
        println!("You said: {input}");
    }

If i run this code, and type `a`, what will be printed?
"""